export const ACTIONS = {
  ADD_POSTS: "ADD_POSTS",
  ADD_POST: "ADD_POST",
  CLEAR_POST: "CLEAR_POST",
  REGISTRATION_FAILURE: "REGISTRATION_FAILURE",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
};
